groups:
  - name: ec2
    rules:
      - alert: InstanceDown
        expr: up == 0
        for: 1m
        labels:
          severity: Critical
        annotations:
          summary: Instance Down
#      - alert: CPUUsageHigh
#        expr: up == 0
#        for: 1m
#        labels:
#          severity: Critical
#        annotations:
#          summary: CPU Usage High
#          description: CPU Usage is High on {{ $labels.instance }}
